name: all

defaults:
  run:
    shell: bash -el {0}

on:
  push:
    branches: [ main ]

jobs:
  main:
    strategy:
      matrix:
        platform: [ubuntu, macos, windows]
        pythonpkg: [conda, pip]
        disable-jit: [1, 0]
        python-version: ["3.10"]
      fail-fast: false
    runs-on: ${{ matrix.platform }}-latest
    steps:
      - uses: actions/checkout@v2
      - if: matrix.pythonpkg == 'conda'
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          activate-environment: test
          python-version: ${{ matrix.python-version }}
      - if: matrix.pythonpkg == 'pip'
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - if: matrix.pythonpkg == 'conda'
        run: conda install numba scipy
      - if: matrix.pythonpkg == 'pip'
        run: python3 -m pip install numba scipy
      - env:
          NUMBA_DISABLE_JIT: ${{ matrix.disable-jit }} 
        run: |
          python3 --version
          for run in {1..1000}; do 
            echo "RUN: $run"
            python3 numba_scipy_bug.py
          done
        
