name: all

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]

jobs:
  main:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        pythonpkg: [conda, pip]
        disable_jit: ["1", "0"]
        python-version: ["3.11"]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - if: matrix.pythonpkg == 'conda'
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: ""
          python-version: ${{ matrix.python-version }}
      - if: matrix.pythonpkg == 'pip'
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - if: matrix.pythonpkg == 'conda'
        run: conda install numba scipy
      - if: matrix.pythonpkg == 'pip'
        run: pip install numba scipy
      - env:
          NUMBA_DISABLE_JIT: ${{ matrix.disable-jit }} 
        run: |
          python --version
          for run in {1..1000}; do python numba_scipy_bug.py; done
        
